# REUSE.toml (spec 3.3): machine-readable licensing for every file in
# this repository, landed by .github#214's sweep. 0BSD — the
# public-domain-equivalent, OSI-approved, zero-condition licence —
# because a test fixture should demand nothing of anyone who reads it.
# Aggregate precedence over the whole tree: configuration and workflows
# do not carry per-file headers.
#
# DECIDED (#155): `**` and Cargo.toml's `MIT OR Apache-2.0` differ on
# purpose, and `**` is the statement about these files. Every file here,
# crate sources included, is 0BSD; the lab is a fixture and nothing in
# it is withheld from anyone. Cargo.toml's dual licence is a fixture
# INPUT, not a competing claim: it drives a compound SPDX expression
# through wasm-pack -> package.json -> npm so that path is exercised
# (every published @monumental-archive/lab-wasm carries it), and it
# keeps the workspace crates inside deny.toml's allowlist, which has no
# 0BSD entry and is a canon decision rather than a repo edit. One
# copyright holder throughout, so both grants hold at once and the
# broader of the two is the one on the source. Do not reconcile them,
# and do not build a linter that compares the two expressions: on this
# repo it reports a finding where the answer is "deliberate".
version = 1
SPDX-PackageName = "release-lab"
SPDX-PackageSupplier = "Carl Allen <carl.allen313@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/monumental-archive/release-lab"

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Carl Allen"
SPDX-License-Identifier = "0BSD"
